project:
  type: website

website:
  title: "Henry Rodman"
  site-url: https://hrodmn.dev
  repo-url: https://github.com/hrodmn/hrodmn.dev
  repo-actions: [source]
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
    right:
      - icon: github
        href: https://github.com/hrodmn/
      - icon: rss
        href: index.xml

format:
  html:
    theme: flatly
    css: styles.css
    toc: true

execute:
  freeze: auto