project:
  type: website

website:
  title: "Henry Rodman"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: lux
    css: styles.css
    toc: true

execute:
  freeze: auto