project:
  type: website

website:
  title: "hrodmn.dev"
  site-url: https://hrodmn.dev
  repo-url: https://github.com/hrodmn/hrodmn.dev
  repo-actions: [source]
  twitter-card: true
  google-analytics: "G-3F77E5H78E"
  navbar:
    right:
      - text: about
        href: about.qmd
      - icon: github
        href: https://github.com/hrodmn/
      - icon: rss
        href: index.xml

format:
  html:
    theme: flatly
    css: styles.css
    toc: true

execute:
  freeze: false