project:
  type: website

website:
  title: "hrodmn.dev"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
  sidebar:
    style: "docked"
    search: true
    contents: auto

format:
  html:
    theme: lux
    css: styles.css
    toc: true

execute:
  freeze: auto