on:
  workflow_dispatch:
  pull_request:
    branches: main
  push:
    branches: main

name: Quarto Render and Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2 

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          tinytex: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x' # Version range or exact version of a Python version to use, using SemVer's version range syntax
          cache: 'pip'
      
      - name: Set up docker
        uses: docker-practice/actions-setup-docker@1.0.11
        timeout-minutes: 12

      - name: Install system dependencies
        run: sudo apt update && sudo apt install ghostscript python3-tk

      - name: Install Python packages
        run: pip install -r requirements.txt

      - name: Make .netrc
        env:
          NETRC_LOGIN: ${{ secrets.NETRC_LOGIN }}
          NETRC_PASSWORD: ${{ secrets.NETRC_PASSWORD }}
        run: |
          cat <<EOT > ~/.netrc
          machine urs.earthdata.nasa.gov
          login ${NETRC_LOGIN}
          password ${NETRC_PASSWORD}
          EOT

      - name: Render
        env:
          CPL_VSIL_CURL_USE_HEAD: FALSE
          CPL_CURL_VERBOSE: YES
          GDAL_DISABLE_READDIR_ON_OPEN: YES
          GDAL_HTTP_COOKIEJAR: /tmp/cookies.txt
          GDAL_HTTP_COOKIEFILE: /tmp/cookies.txt
        uses: quarto-dev/quarto-actions/render@v2

      - name: Publish 
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: netlify
          render: "false"
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}